name: autosign

on: 
  #push:
  schedule: 
    - cron: '10 16 * * *'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # npm install
    - name: run
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        TGTOKEN: ${{ secrets.TGTOKEN }}
        TGCHATID: ${{ secrets.TGCHATID }}
      run: |
        echo $(date +%F%n%T)
        node index.js
